/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emerging_cw;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;

/**
 *
 * @author Aashna, Rabina, Subriti
 */
public class homeGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public homeGUI() {
        initComponents();
        loginAdmin_jPanel.setVisible(false);
        loginMember_jPanel.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_jPanel = new javax.swing.JPanel();
        academy_jlabel = new javax.swing.JLabel();
        academyAddress_jlabel = new javax.swing.JLabel();
        home_jPanel = new javax.swing.JPanel();
        academyimage_jLabel = new javax.swing.JLabel();
        users_jPanel = new javax.swing.JPanel();
        admin_jButton = new javax.swing.JButton();
        registermember_jButton = new javax.swing.JButton();
        member_jButton = new javax.swing.JButton();
        newAccount_jLabel = new javax.swing.JLabel();
        loginAdmin_jPanel = new javax.swing.JPanel();
        admin_jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        loginMember_jPanel = new javax.swing.JPanel();
        admin_jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        memberNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        memberPasswordField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        BackButton_Registration = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        name_jLabel = new javax.swing.JLabel();
        specialization_jLabel = new javax.swing.JLabel();
        age_jLabel = new javax.swing.JLabel();
        username_jLabel = new javax.swing.JLabel();
        password_jLabel = new javax.swing.JLabel();
        name_jTextField = new javax.swing.JTextField();
        age_jTextField = new javax.swing.JTextField();
        specialization_jTextField = new javax.swing.JTextField();
        username_jTextField = new javax.swing.JTextField();
        repassword_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemberInfo_jTable = new javax.swing.JTable();
        password_jPasswordField = new javax.swing.JPasswordField();
        repassword_jPasswordField = new javax.swing.JPasswordField();
        Submit_jButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        backgroundimage_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main_Frame");
        setBackground(new java.awt.Color(230, 244, 254));
        setBounds(new java.awt.Rectangle(390, 180, 0, 0));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        main_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        main_jPanel.setLayout(null);

        academy_jlabel.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        academy_jlabel.setForeground(new java.awt.Color(51, 153, 255));
        academy_jlabel.setText("Serene  Music Academy.");
        main_jPanel.add(academy_jlabel);
        academy_jlabel.setBounds(230, 30, 300, 44);

        academyAddress_jlabel.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        academyAddress_jlabel.setForeground(new java.awt.Color(102, 204, 255));
        academyAddress_jlabel.setText("Kamalpokhari, Kathmandu, Nepal.");
        academyAddress_jlabel.setIconTextGap(0);
        academyAddress_jlabel.setMaximumSize(new java.awt.Dimension(0, 0));
        main_jPanel.add(academyAddress_jlabel);
        academyAddress_jlabel.setBounds(290, 80, 220, 18);

        home_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        home_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        home_jPanel.setForeground(new java.awt.Color(255, 255, 255));

        academyimage_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/music.png"))); // NOI18N
        academyimage_jLabel.setText("jLabel2");

        users_jPanel.setBackground(new java.awt.Color(64, 132, 173));
        users_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(17, 102, 153)));
        users_jPanel.setToolTipText("");
        users_jPanel.setPreferredSize(new java.awt.Dimension(238, 257));

        admin_jButton.setBackground(new java.awt.Color(190, 190, 253));
        admin_jButton.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        admin_jButton.setForeground(new java.awt.Color(51, 120, 156));
        admin_jButton.setText("Admin");
        admin_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jButtonActionPerformed(evt);
            }
        });

        registermember_jButton.setBackground(new java.awt.Color(190, 190, 253));
        registermember_jButton.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        registermember_jButton.setForeground(new java.awt.Color(51, 120, 156));
        registermember_jButton.setText("Register");
        registermember_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registermember_jButtonActionPerformed(evt);
            }
        });

        member_jButton.setBackground(new java.awt.Color(190, 190, 253));
        member_jButton.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        member_jButton.setForeground(new java.awt.Color(51, 120, 156));
        member_jButton.setText("Member");
        member_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_jButtonActionPerformed(evt);
            }
        });

        newAccount_jLabel.setText("Create new account?");

        javax.swing.GroupLayout users_jPanelLayout = new javax.swing.GroupLayout(users_jPanel);
        users_jPanel.setLayout(users_jPanelLayout);
        users_jPanelLayout.setHorizontalGroup(
            users_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, users_jPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(users_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(member_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registermember_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(users_jPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(newAccount_jLabel)))
                .addGap(29, 29, 29))
        );
        users_jPanelLayout.setVerticalGroup(
            users_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, users_jPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(admin_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(member_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(newAccount_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registermember_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        loginAdmin_jPanel.setBackground(new java.awt.Color(64, 132, 173));
        loginAdmin_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(17, 102, 153)));
        loginAdmin_jPanel.setToolTipText("");
        loginAdmin_jPanel.setPreferredSize(new java.awt.Dimension(238, 257));

        admin_jButton1.setBackground(new java.awt.Color(190, 190, 253));
        admin_jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        admin_jButton1.setForeground(new java.awt.Color(51, 120, 156));
        admin_jButton1.setText("Login ");
        admin_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Password");

        jTextField2.setText("jTextField1");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginAdmin_jPanelLayout = new javax.swing.GroupLayout(loginAdmin_jPanel);
        loginAdmin_jPanel.setLayout(loginAdmin_jPanelLayout);
        loginAdmin_jPanelLayout.setHorizontalGroup(
            loginAdmin_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAdmin_jPanelLayout.createSequentialGroup()
                .addGroup(loginAdmin_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginAdmin_jPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2))
                    .addGroup(loginAdmin_jPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdmin_jPanelLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(loginAdmin_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdmin_jPanelLayout.createSequentialGroup()
                        .addGroup(loginAdmin_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        loginAdmin_jPanelLayout.setVerticalGroup(
            loginAdmin_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginAdmin_jPanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(admin_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        loginMember_jPanel.setBackground(new java.awt.Color(64, 132, 173));
        loginMember_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(17, 102, 153)));
        loginMember_jPanel.setToolTipText("");
        loginMember_jPanel.setPreferredSize(new java.awt.Dimension(238, 257));

        admin_jButton2.setBackground(new java.awt.Color(190, 190, 253));
        admin_jButton2.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        admin_jButton2.setForeground(new java.awt.Color(51, 120, 156));
        admin_jButton2.setText("Login ");
        admin_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        memberNameField.setText("jTextField1");

        jLabel4.setText("Password");

        memberPasswordField.setText("jTextField1");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginMember_jPanelLayout = new javax.swing.GroupLayout(loginMember_jPanel);
        loginMember_jPanel.setLayout(loginMember_jPanelLayout);
        loginMember_jPanelLayout.setHorizontalGroup(
            loginMember_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMember_jPanelLayout.createSequentialGroup()
                .addGroup(loginMember_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginMember_jPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4))
                    .addGroup(loginMember_jPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMember_jPanelLayout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(loginMember_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMember_jPanelLayout.createSequentialGroup()
                        .addGroup(loginMember_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(memberNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memberPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        loginMember_jPanelLayout.setVerticalGroup(
            loginMember_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMember_jPanelLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(memberPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(admin_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout home_jPanelLayout = new javax.swing.GroupLayout(home_jPanel);
        home_jPanel.setLayout(home_jPanelLayout);
        home_jPanelLayout.setHorizontalGroup(
            home_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(academyimage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(users_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginAdmin_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginMember_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        home_jPanelLayout.setVerticalGroup(
            home_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_jPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(home_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginMember_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(academyimage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginAdmin_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        main_jPanel.add(home_jPanel);
        home_jPanel.setBounds(27, 142, 680, 300);

        jPanel3.setBackground(new java.awt.Color(230, 244, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        BackButton_Registration.setText("Back");
        BackButton_Registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton_RegistrationActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Registration");

        name_jLabel.setText("Name ");

        specialization_jLabel.setText("Specialization");

        age_jLabel.setText(" Age");

        username_jLabel.setText(" Username");

        password_jLabel.setText(" Password");

        specialization_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialization_jTextFieldActionPerformed(evt);
            }
        });

        repassword_jLabel.setText("Re-type Password");

        MemberInfo_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Specialization", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(MemberInfo_jTable);

        password_jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_jPasswordFieldActionPerformed(evt);
            }
        });

        Submit_jButton.setText("Submit");
        Submit_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BackButton_Registration)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age_jLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(name_jLabel)
                                        .addGap(48, 48, 48))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(specialization_jLabel)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(specialization_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(age_jTextField))
                                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(password_jLabel)
                                    .addComponent(repassword_jLabel)
                                    .addComponent(username_jLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password_jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(repassword_jPasswordField)
                                    .addComponent(username_jTextField))))
                        .addGap(116, 116, 116))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(Submit_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_jLabel)
                            .addComponent(password_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(repassword_jLabel)
                            .addComponent(repassword_jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_jLabel)
                            .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialization_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(specialization_jLabel))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Submit_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton_Registration)
                        .addGap(75, 75, 75))))
        );

        main_jPanel.add(jPanel3);
        jPanel3.setBounds(27, 142, 680, 300);

        jPanel4.setBackground(new java.awt.Color(230, 244, 254));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Admin and Instruments");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel6)
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        main_jPanel.add(jPanel4);
        jPanel4.setBounds(27, 142, 680, 300);

        backgroundimage_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Music Notes.png"))); // NOI18N
        backgroundimage_jLabel.setMinimumSize(new java.awt.Dimension(500, 700));
        backgroundimage_jLabel.setPreferredSize(new java.awt.Dimension(1000, 1080));
        main_jPanel.add(backgroundimage_jLabel);
        backgroundimage_jLabel.setBounds(0, 0, 760, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        main_jPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jButtonActionPerformed
        // TODO add your handling code here:
        loginAdmin_jPanel.setVisible(true);
        users_jPanel.setVisible(false);
        loginMember_jPanel.setVisible(false);
    }//GEN-LAST:event_admin_jButtonActionPerformed

    private void registermember_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registermember_jButtonActionPerformed
        // TODO add your handling code here:
        main_jPanel.setVisible(true);
        home_jPanel.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        
        
    }//GEN-LAST:event_registermember_jButtonActionPerformed

    private void member_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_jButtonActionPerformed
        // TODO add your handling code here:
        loginAdmin_jPanel.setVisible(false);
        users_jPanel.setVisible(false);
        loginMember_jPanel.setVisible(true);
    }//GEN-LAST:event_member_jButtonActionPerformed

    private void admin_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        main_jPanel.setVisible(true);
        home_jPanel.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_admin_jButton1ActionPerformed

    private void admin_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jButton2ActionPerformed
        // TODO add your handling code here:
        String enteredUserName = memberNameField.getText();
        String enteredPassword = memberPasswordField.getText();
       
       if(loginMap.containsKey(enteredUserName)){
           String storedPassword = loginMap.get(enteredUserName);
           if(enteredPassword.equals(storedPassword)){
               System.out.println("Login Successful");
           }
           else{
               System.out.println("Nooooooooooo");
           }
        
       }
       else{
           System.out.println("User not found");
       }
    }//GEN-LAST:event_admin_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loginAdmin_jPanel.setVisible(false);
        users_jPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         loginMember_jPanel.setVisible(false);
        users_jPanel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackButton_RegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton_RegistrationActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        home_jPanel.setVisible(true);
    }//GEN-LAST:event_BackButton_RegistrationActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        home_jPanel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void password_jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_jPasswordFieldActionPerformed

    private void specialization_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialization_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialization_jTextFieldActionPerformed

    private void Submit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_jButtonActionPerformed
        // TODO add your handling code here:
        String period="";
        String name= name_jTextField.getText();
        String age= age_jTextField.getText();
        String specialization= specialization_jTextField.getText();
        String username= username_jTextField.getText();
        String password= password_jPasswordField.getText();        
        
        String[]values= {name,age,specialization,username,password};
        int rowCount= MemberInfo_jTable.getRowCount();
        int columnCount= MemberInfo_jTable.getColumnCount();
        int rowIndex=0;
        do
        {
            String s= (String)MemberInfo_jTable.getValueAt(rowIndex,0);
            if (s!= null && s.length()!=0)
            {
                rowIndex++;
            }
            else
            {
                break;
            }
        }
        while (rowIndex<rowCount);
        for (int i=0; i<columnCount; i++)
        {
            MemberInfo_jTable.setValueAt(values[i],rowIndex,i);
        }
    }//GEN-LAST:event_Submit_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    static HashMap<String, String> loginMap;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        loginMap = new HashMap<>();
        try{
            FileReader fileReader = new FileReader("src/CSV_Files/Members.csv");
            BufferedReader csvReader = new BufferedReader(fileReader);
            
            String row;
           
            boolean isFirstLine = true;
            while ((row = csvReader.readLine())!=null){
                //skip first line
                if(isFirstLine){
                    isFirstLine = false;
                    continue;
                }
                String loginDetails[] = row.split(",");
                String userName = loginDetails[3];
                String password = loginDetails[4];
                loginMap.put(userName, password);
            }
            fileReader.close();
            csvReader.close();
        }
        catch(FileNotFoundException e){System.out.println("File not found");}
        catch(IOException ioe) {System.out.println("IO Exception");}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeGUI().setVisible(true);
            }
        });
    }                                                

    private void Exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton_Registration;
    private javax.swing.JTable MemberInfo_jTable;
    private javax.swing.JButton Submit_jButton;
    private javax.swing.JLabel academyAddress_jlabel;
    private javax.swing.JLabel academy_jlabel;
    private javax.swing.JLabel academyimage_jLabel;
    private javax.swing.JButton admin_jButton;
    private javax.swing.JButton admin_jButton1;
    private javax.swing.JButton admin_jButton2;
    private javax.swing.JLabel age_jLabel;
    private javax.swing.JTextField age_jTextField;
    private javax.swing.JLabel backgroundimage_jLabel;
    private javax.swing.JPanel home_jPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel loginAdmin_jPanel;
    private javax.swing.JPanel loginMember_jPanel;
    private javax.swing.JPanel main_jPanel;
    private javax.swing.JTextField memberNameField;
    private javax.swing.JTextField memberPasswordField;
    private javax.swing.JButton member_jButton;
    private javax.swing.JLabel name_jLabel;
    private javax.swing.JTextField name_jTextField;
    private javax.swing.JLabel newAccount_jLabel;
    private javax.swing.JLabel password_jLabel;
    private javax.swing.JPasswordField password_jPasswordField;
    private javax.swing.JButton registermember_jButton;
    private javax.swing.JLabel repassword_jLabel;
    private javax.swing.JPasswordField repassword_jPasswordField;
    private javax.swing.JLabel specialization_jLabel;
    private javax.swing.JTextField specialization_jTextField;
    private javax.swing.JLabel username_jLabel;
    private javax.swing.JTextField username_jTextField;
    private javax.swing.JPanel users_jPanel;
    // End of variables declaration//GEN-END:variables
}
