/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emerging_cw;

/**
 *
 * @author Rabina
 */
public class homeGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public homeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainframe_jPanel = new javax.swing.JPanel();
        academy_jlabel = new javax.swing.JLabel();
        academyAddress_jlabel = new javax.swing.JLabel();
        main_jPanel = new javax.swing.JPanel();
        login_jPanel = new javax.swing.JPanel();
        admin_jButton = new javax.swing.JButton();
        member_jButton = new javax.swing.JButton();
        academyimage_jLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backgroundimage_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main_Frame");
        setBackground(new java.awt.Color(230, 244, 254));
        setBounds(new java.awt.Rectangle(390, 180, 0, 0));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        mainframe_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        mainframe_jPanel.setLayout(null);

        academy_jlabel.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        academy_jlabel.setForeground(new java.awt.Color(51, 153, 255));
        academy_jlabel.setText("Serene  Music Academy.");
        mainframe_jPanel.add(academy_jlabel);
        academy_jlabel.setBounds(230, 30, 300, 44);

        academyAddress_jlabel.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        academyAddress_jlabel.setForeground(new java.awt.Color(102, 204, 255));
        academyAddress_jlabel.setText("Kamalpokhari, Kathmandu, Nepal.");
        academyAddress_jlabel.setIconTextGap(0);
        academyAddress_jlabel.setMaximumSize(new java.awt.Dimension(0, 0));
        mainframe_jPanel.add(academyAddress_jlabel);
        academyAddress_jlabel.setBounds(290, 80, 220, 18);

        main_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        main_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        main_jPanel.setForeground(new java.awt.Color(255, 255, 255));

        login_jPanel.setBackground(new java.awt.Color(64, 132, 173));
        login_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, new java.awt.Color(17, 102, 153)));
        login_jPanel.setToolTipText("");

        admin_jButton.setBackground(new java.awt.Color(190, 190, 253));
        admin_jButton.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        admin_jButton.setForeground(new java.awt.Color(51, 120, 156));
        admin_jButton.setText("Admin");
        admin_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_jButtonActionPerformed(evt);
            }
        });

        member_jButton.setBackground(new java.awt.Color(190, 190, 253));
        member_jButton.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        member_jButton.setForeground(new java.awt.Color(51, 120, 156));
        member_jButton.setText("User");
        member_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_jPanelLayout = new javax.swing.GroupLayout(login_jPanel);
        login_jPanel.setLayout(login_jPanelLayout);
        login_jPanelLayout.setHorizontalGroup(
            login_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_jPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(login_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(member_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        login_jPanelLayout.setVerticalGroup(
            login_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_jPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(admin_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(member_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        academyimage_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/music.png"))); // NOI18N
        academyimage_jLabel.setText("jLabel2");

        javax.swing.GroupLayout main_jPanelLayout = new javax.swing.GroupLayout(main_jPanel);
        main_jPanel.setLayout(main_jPanelLayout);
        main_jPanelLayout.setHorizontalGroup(
            main_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(academyimage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        main_jPanelLayout.setVerticalGroup(
            main_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(main_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(academyimage_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        mainframe_jPanel.add(main_jPanel);
        main_jPanel.setBounds(27, 142, 680, 300);

        jPanel3.setBackground(new java.awt.Color(230, 244, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        mainframe_jPanel.add(jPanel3);
        jPanel3.setBounds(27, 142, 680, 300);

        backgroundimage_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Music Notes.png"))); // NOI18N
        backgroundimage_jLabel.setMinimumSize(new java.awt.Dimension(500, 700));
        backgroundimage_jLabel.setPreferredSize(new java.awt.Dimension(1000, 1080));
        mainframe_jPanel.add(backgroundimage_jLabel);
        backgroundimage_jLabel.setBounds(0, 0, 760, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainframe_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainframe_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainframe_jPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_jButtonActionPerformed

    private void member_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_jButtonActionPerformed
        // TODO add your handling code here:
        mainframe_jPanel.setVisible(true);
        main_jPanel.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_member_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academyAddress_jlabel;
    private javax.swing.JLabel academy_jlabel;
    private javax.swing.JLabel academyimage_jLabel;
    private javax.swing.JButton admin_jButton;
    private javax.swing.JLabel backgroundimage_jLabel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login_jPanel;
    private javax.swing.JPanel main_jPanel;
    private javax.swing.JPanel mainframe_jPanel;
    private javax.swing.JButton member_jButton;
    // End of variables declaration//GEN-END:variables
}
