/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emerging_cw;

/**
 *
 * @author Rabina
 */
public class memberRegistrationGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public memberRegistrationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainframe_jPanel = new javax.swing.JPanel();
        academy_jlabel = new javax.swing.JLabel();
        address_jlabel = new javax.swing.JLabel();
        main_jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backgroundimage_jLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main_Frame");
        setBackground(new java.awt.Color(230, 244, 254));
        setBounds(new java.awt.Rectangle(390, 180, 0, 0));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        mainframe_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        mainframe_jPanel.setLayout(null);

        academy_jlabel.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        academy_jlabel.setForeground(new java.awt.Color(51, 153, 255));
        academy_jlabel.setText("Serene  Music Academy.");
        mainframe_jPanel.add(academy_jlabel);
        academy_jlabel.setBounds(230, 30, 300, 44);

        address_jlabel.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N
        address_jlabel.setForeground(new java.awt.Color(102, 204, 255));
        address_jlabel.setText("Kamalpokhari, Kathmandu, Nepal.");
        address_jlabel.setIconTextGap(0);
        address_jlabel.setMaximumSize(new java.awt.Dimension(0, 0));
        mainframe_jPanel.add(address_jlabel);
        address_jlabel.setBounds(290, 80, 220, 18);

        main_jPanel.setBackground(new java.awt.Color(230, 244, 254));
        main_jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        main_jPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("First Name:");

        javax.swing.GroupLayout main_jPanelLayout = new javax.swing.GroupLayout(main_jPanel);
        main_jPanel.setLayout(main_jPanelLayout);
        main_jPanelLayout.setHorizontalGroup(
            main_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        main_jPanelLayout.setVerticalGroup(
            main_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        mainframe_jPanel.add(main_jPanel);
        main_jPanel.setBounds(27, 142, 680, 300);

        backgroundimage_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Music Notes.png"))); // NOI18N
        backgroundimage_jLabel.setMinimumSize(new java.awt.Dimension(500, 700));
        backgroundimage_jLabel.setPreferredSize(new java.awt.Dimension(1000, 1080));
        mainframe_jPanel.add(backgroundimage_jLabel);
        backgroundimage_jLabel.setBounds(0, 0, 760, 470);

        jPanel3.setBackground(new java.awt.Color(230, 244, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(26, 175, 247)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        mainframe_jPanel.add(jPanel3);
        jPanel3.setBounds(27, 142, 680, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainframe_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainframe_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        mainframe_jPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memberRegistrationGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academy_jlabel;
    private javax.swing.JLabel address_jlabel;
    private javax.swing.JLabel backgroundimage_jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel main_jPanel;
    private javax.swing.JPanel mainframe_jPanel;
    // End of variables declaration//GEN-END:variables
}
